steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webwatch-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/webwatch-api:latest'

  # Deploy container image to Cloud Run with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'webwatch-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/webwatch-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=sitegrip-firestore'
      - '--update-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest,FIREBASE_WEB_API_KEY=firebase-web-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/webwatch-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY 