steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/webwatch-api'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/webwatch-api'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'webwatch-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/webwatch-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '600s'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},FIREBASE_WEB_API_KEY=${_FIREBASE_WEB_API_KEY},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI}'

images:
  - 'gcr.io/$PROJECT_ID/webwatch-api'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GEMINI_API_KEY: ''
  _FIREBASE_WEB_API_KEY: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _GOOGLE_REDIRECT_URI: '' 